ARG PYTHON_VERSION=3.9.12-alpine3.15

FROM docker.io/arm64v8/python:${PYTHON_VERSION}

LABEL maintainer "Lorenzo Prosseda <lerokamut@gmail.com>"

COPY qemu-aarch64-static /usr/bin/

ENV PYTHONUNBUFFERED 1
ENV TZ Europe/Rome
ADD ./app /app

RUN pip install --no-cache-dir -r /app/requirements.txt

WORKDIR /app

RUN rm -rf /usr/bin/qemu-aarch64-static

ENTRYPOINT ["python3", "main.py"]
