version: "3"
services:
    app:
        image: docker.io/procsiab/foodpod:1.3-amd64
        volumes:
            - ./.secrets:/auth:Z
        restart: unless-stopped
        env:
            - REDIS_HOST="compose_db_1"
            - REDIS_PORT="6379"
            - REDIS_DB="0"
            - REDIS_PASS=""
            - TZ="Europe/Rome"
    db:
        image: docker.io/library/redis:6.2.6-alpine
        volumes:
            - .redis:/data:Z
        command: ["redis-server", "--appendonly", "yes"]
