ARG PYTHON_VERSION=3.9.12-alpine3.15

FROM docker.io/amd64/python:${PYTHON_VERSION}

LABEL maintainer "Lorenzo Prosseda <lerokamut@gmail.com>"

ENV PYTHONUNBUFFERED 1
ENV TZ Europe/Rome
ADD ./app /app

RUN pip install --no-cache-dir -r /app/requirements.txt

WORKDIR /app

ENTRYPOINT ["python3", "main.py"]
